### ISSUE TITLE
dmarc-report-viewer dont see dmarc reports from IMAP mailbox

### ISSUE THREAD

**Issue by swarnk** [cry-inc/dmarc-report-viewer#1] opened 2024-09-27 13:39 UTC
Hello!
Thank you for your work!
dmarc-report-viewer dont see dmarc reports from IMAP mailbox.
Run from docker.
But this IMAP mailbox contain many mails with Dmarc reports.

2024-09-27T13:32:18.981811Z  INFO DMARC Report Analyzer
2024-09-27T13:32:18.981842Z  INFO Log Level: INFO
2024-09-27T13:32:18.981906Z  INFO Started background task with check interval of 1000 secs
2024-09-27T13:32:18.981951Z  INFO Starting background update cycle
2024-09-27T13:32:18.983623Z  INFO Binding HTTP server to 0.0.0.0:8123...
2024-09-27T13:32:20.413447Z  INFO Downloaded metadata of 14663 mails
2024-09-27T13:32:20.424401Z  INFO Downloaded 14663 mails
2024-09-27T13:32:20.429913Z  INFO Extracted 0 XML files from mails
2024-09-27T13:32:20.429935Z  INFO Parsed 0 DMARC reports successfully
2024-09-27T13:32:20.429940Z  INFO Finished updating shared state
2024-09-27T13:32:20.429944Z  INFO Finished update cycle without errors

**Comment by cry-inc** [comment] 2024-09-28 09:31
Hi and thanks for showing interest in this project!

I have to admit, I never tested it with larger inboxes. But luckily I was able to reproduce your issue by duplicating the mails from a smaller mailbox.

Turns out there were two issues:
* The logging was in some cases wrong. The line "Downloaded 14663 mails" was not actually true and it downloaded zero mails instead. This has been now fixed.
* The root cause was that requesting all mails together in one request stops working between 12000 and 13000 mails. At least for me and my IMAP server. I fixed that by requesting them now in chunks with a maximal size of 5000 mails per request.

Both issues should be fixed now! If you are interested, you can find the fixes here: https://github.com/cry-inc/dmarc-report-viewer/commit/613d29e089e2852d1ecb7327229553407411e4f3

Please let me know if it works now as expected!

**Comment by swarnk** [comment] 2024-09-28 14:18
Great! Thank you for useful tool!
It work now as expected!
i am searching  lightweight  software for analyse dmarc report, but many of them using ELK stack (too overkill for me).
Your tool ideal for my purposet!

**Comment by cry-inc** [comment] 2024-09-28 21:54
Perfect. The lightweigt aspect and being able to just check the reports without a lot of overhead was my main motivation.
Also, feel free to create feature request issues if you need something thats still missing and would be useful for you!

**Closed by cry-inc** 2024-09-28 21:54 UTC
